snorkel-team/snorkel-tutorials

mtl/multitask_tutorial.ipynb
mtl/multitask_tutorial.py

- Add section to the end of the MTL tutorial where the user has the chance to test their understanding (create appropriate dataloaders and task object, then construct 3-task model and test that it worked)
Test plan:
`tox -e mtl`

Add MTL "playground" section to tutorial

---

crowdsourcing/crowdsourcing_tutorial.ipynb
crowdsourcing/crowdsourcing_tutorial.py
crowdsourcing/requirements.txt

Use average of bert embeddings in final layer to get features, and sklearn LR on top of the features to get an accuracy of 0.86 (as compared to ~0.72 with bag of ngrams).
**Test Plan**
tox -e crowd / style pass

Switch to using BERT features

---

spam/spam_tutorial.ipynb
spam/spam_tutorial.py

Address form comments

---

spam/spam_tutorial.ipynb
spam/spam_tutorial.py

Address remaining spam tutorial comments from feedback session.
**Test Plan**
tox passes

Address more comments

---

scene_graph/download_data.sh
scene_graph/vrd_tutorial.ipynb
scene_graph/vrd_tutorial.py

1. Switch from svn to git, (reducing one dependency at the cost of downloading 26MB instead of 13MB).
2. Reword statement about train_df having -1 labels before train_df was defined.
3. Make F1 definition link clearer.
**Test Plan**
tox -e scene_graph passes

Address Thursday comments for scene graph tutorial.

---

README.md

Needs more work, but update things that are obviously wrong

[EASY] Hotfix the index

---

spouse/spouse_demo.py

* Change seed for LabelModel
* Change accuracy to F1

Improve LabelModel Performance

---

.gitignore

Add nohup and swp files to gitignore

---

crowdsourcing/crowdsourcing_tutorial.ipynb
crowdsourcing/crowdsourcing_tutorial.py

LF names weren't unique
**Test plan**
Travis

Hot fix LF names

---

scripts/build.py

Parse links in .py files, then see if they return a 4XX code. Tested manually several times, and caught a bad link! Importantly, checked this finds bad readthedocs links

Add link checking

---

.travis.yml
scripts/docker_launch.py
scripts/get_tox_envs.py

Analyze files changed in Travis patch. If there's only one subdirectory and it's one of our Travis environments, just run that one. Otherwise, run all. If it's not a PR (i.e. on master), run all.
**Test plan**
* Tested a bunch of configurations locally
* Will monitor as this deploys

Only run Travis on changed tutorials

---

scripts/get_tox_envs.py

Really need to educate myself about sets...

Fix Travis branch check

---

scripts/get_tox_envs.py

If we just run one tutorial, should still run style. Can add extra envs in a generic way.
**Test plan**
Tested locally

Add style to run envs

---

scripts/build.py
tox.ini

Also: robust to more link checking issues and remove `mtl`
**Test plan**
Tested locally

More verbose build script

---

.web.yml
scripts/build.py
tox.ini

Run `tox -e markdown` to generate all markdown webpages. Just add the page you want to .web.yml. Will deploy via Travis in next PR.
**Test plan**
Testing locally

Configure markdown generation

---

.travis.yml
.web.yml
scripts/push-tutorials.sh

Deploy tutorial pages via Travis

---

.travis.yml
scripts/get_tox_envs.py
scripts/push-tutorials.sh

Biffed on `test` command before, so removing.
**Test plan**
Manual log check, local command execution

Fix deploy

---

README.md

**Test Plan**
Tested spouse and crowd tutorials with new conda instructions on an AWS instance with Deep Learning AMI (ubuntu) p3.2xlarge. spam is failing due to unrelated bug.

Update conda instructions

---

spam/01_spam_tutorial.py

[EASY] Add full reference to spam dataset

---

tox.ini

Remove scene_graph environment [EASY]

---

README.md

if it's spam, it spits out the env contents into the spam dir which is confusing
**Test plan**
Ran locally

Avoid dir name collision

---

.web.yml
CONTRIBUTING.md
crowdsourcing/crowdsourcing_tutorial.ipynb
crowdsourcing/crowdsourcing_tutorial.py
scripts/build.py

1. Turns on output rendering for all but getting started
2. Adds finer control for rendering outputs (see crowdsourcing)
3. Improves output rendering for crowdsourcing
4. Updates documentation
**Test plan**
Local markdown builds
Manual render checks

Restore output rendering

---

visual_relation/model.py
visual_relation/visual_relation_tutorial.ipynb
visual_relation/visual_relation_tutorial.py

Visual Relation pass

---

scripts/build.py
scripts/push-tutorials.sh

Tested locally on TFs, crowd, and getting_started

Add GitHub link to header

---

multitask/multitask_tutorial.ipynb
multitask/multitask_tutorial.py

Ignore output of cells unnecessary for markdown tutorial.

Add markdown exclusions for multitask tutorial

---

visual_relation/download_full_data.sh
visual_relation/download_sample_data.sh
visual_relation/model.py
visual_relation/utils.py
visual_relation/visual_relation_tutorial.ipynb
visual_relation/visual_relation_tutorial.py

**Test Plan**
tox -e visual_relation
tox -e style
Tried running with and without pre-existing data directory.

Make visual_relation run from visual_relation directory for consistency

---

multitask/multitask_tutorial.ipynb
multitask/multitask_tutorial.py

Just what it says.
The bottom paragraph has no changes; just putting each sentence on a newline for better versioning in the future.

[EASY] link to slicing tutorial

---

README.md
crowdsourcing/README.md
getting_started/README.md
multitask/README.md
recsys/README.md
spam/README.md
spouse/README.md
visual_relation/README.md

**Test Plan**
Changes only in readme's.

Add readmes to each tutorial

---

requirements.txt

Pin snorkel version to v0.9.0

---

README.md
spam/01_spam_tutorial.ipynb
spam/01_spam_tutorial.py
spam/02_spam_data_augmentation_tutorial.ipynb
spam/02_spam_data_augmentation_tutorial.py

Set all Snorkel links to https.

Replace http://snorkel.org with https://snorkel.org

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CONTRIBUTING.md
README.md

* Update contrib guidelines
* Added overview
* Added changes to existing section
* Updated new tutorial section
* Added testing section
* Updated markdown generation section
* Add Issues and PR templates
* Small changes to README (badges, contrib)

Overhaul contributing guidelines

---

spam/requirements.txt

Update ntlk version to avoid vulnerability identified by GitHub.
`tox`

Update nltk version

---

.github/workflows/stale.yml

Don't close issues with `feature request`

Add exempt label

---

README.md

Add a badge and note discussing the Snorkel version used in this repo.
Addresses #155 
Doing it live.

Add note on Snorkel version to repo

---

spam/requirements.txt

Fix spam tests by bounding spacy version (new release)
Fixes # https://github.com/snorkel-team/snorkel-tutorials/issues/160 (cc @cyrilou242)
Existing `tox -e spam` tests fixed!

Fix spam tests by bounding spacy version

---

drybell/drybell_dask.py
drybell/drybell_lfs.py
drybell/drybell_lfs_spark.py
drybell/drybell_spark.py

* Update tests to include an additional content-heuristic based LF; satisfies [>=3 LFs for LabelModel](https://github.com/snorkel-team/snorkel/blob/master/snorkel/labeling/model/label_model.py#L595)

Update drybell to include content-heuristic LF

---

spam/03_spam_data_slicing_tutorial.ipynb
spam/03_spam_data_slicing_tutorial.py

Include updated links to slicing technical reports in the tutorial.
* [] All new and existing tests passed.

[EASY] Update links to slicing TR

---

README.md

[EZ] Update README.md

---

.github/workflows/stale.yml

See https://github.com/snorkel-team/snorkel/pull/1511
* [] I have verified that my changes are covered by continuous integration.

Update exempt-issue-label to `no-stale`

---

visual_relation/visual_relation_tutorial.ipynb
visual_relation/visual_relation_tutorial.py

* Add link to recent ICCV paper demonstrating Snorkel + visual relationship detection
* Existing tests pass

[EASY] Add ICCV link to VRD tutorial

---

recsys/requirements.txt

Reverts snorkel-team/snorkel-tutorials#197

Revert "Bump tensorflow from 1.14.0 to 1.15.2 in /recsys"

---

spouse/requirements.txt

Reverts snorkel-team/snorkel-tutorials#196

Revert "Bump tensorflow from 1.14.0 to 1.15.2 in /spouse"

---

spam/requirements.txt

Reverts snorkel-team/snorkel-tutorials#195

Revert "Bump tensorflow from 1.14.0 to 1.15.2 in /spam"

---

crowdsourcing/requirements.txt

Reverts snorkel-team/snorkel-tutorials#194

Revert "Bump tensorflow from 1.14.0 to 1.15.2 in /crowdsourcing"

---

README.md

Updated the snorkel version on the README to the one in requirements.txt
Fixes # (issue)
#221 

Updated snorkel versions on badge and conda installation

---

spam/01_spam_tutorial.ipynb
spam/01_spam_tutorial.py

Fix 404 to data frames tutorial
Fixes a link

Fix 404 to data frames tutorial

---

spouse/download_data.sh

Added --no-check-certificate in downalod_data.sh in the spouse example 
Fixes # (issue)
without --no-check-certificate in line 25 of download_data.sh,  users can't download the file from dropbox since the local envrionment can't verify the issuer's authority.

added --no-check-certificate

---

README.md
requirements.txt
spam/requirements.txt

This PR updates the Snorkel requirements after releasing `v0.9.9` and addresses issues around installing as seen [here](https://github.com/snorkel-team/snorkel-tutorials/issues/286)
Fixes # (issue)
issue #286 
Installed the requirements (both base + spam) and ran the `01_spam_tutorial.ipynb`
* [* ] I have read the **CONTRIBUTING** document.
* [ *] I have verified that my changes are covered by continuous integration.
* [ *] All new and existing tests passed.

Upgrade requirements for new Snorkel release
